apiVersion: v1
kind: Service
metadata:
  name: omniguard-enterprise
spec:
  type: ClusterIP
  ports:
  - port: 5173
    targetPort: 5173
    name: frontend
  - port: 5175
    targetPort: 5175
    name: daemon
  selector:
    app: omniguard-enterprise
