'use strict';
const https = require('https');

/**
 * GitLab Integration — posts MR (merge request) notes and creates issues
 * from OmniGuard findings via GitLab REST API v4.
 * Required env / config:
 *   GITLAB_TOKEN  — Personal Access Token or Project Access Token
 *   GITLAB_URL    — GitLab base URL (default: https://gitlab.com)
 */
class GitlabIntegration {
  constructor() {
    this.token = process.env.GITLAB_TOKEN || '';
    this.baseUrl = process.env.GITLAB_URL || 'https://gitlab.com';
  }

  /**
   * Execute the integration.
   * payload = { projectId, finding, action: 'issue'|'comment', mergeRequestIid }
   */
  async execute(payload = {}) {
    const { projectId, finding, action = 'issue', mergeRequestIid } = payload;
    if (!this.token) {
      console.warn('[GitLab] GITLAB_TOKEN not configured. Skipping GitLab integration.');
      return { skipped: true };
    }
    if (!projectId) {
      console.warn('[GitLab] projectId not provided.');
      return { skipped: true };
    }

    if (action === 'comment' && mergeRequestIid) {
      return this._postMRNote(projectId, mergeRequestIid, finding);
    }
    return this._createIssue(projectId, finding);
  }

  _apiRequest(method, path, body = null) {
    return new Promise((resolve, reject) => {
      const url = new URL(`${this.baseUrl}/api/v4${path}`);
      const options = {
        hostname: url.hostname,
        port: url.port || 443,
        path: url.pathname + url.search,
        method,
        headers: {
          'Content-Type': 'application/json',
          'PRIVATE-TOKEN': this.token
        }
      };

      const protocol = url.protocol === 'http:' ? require('http') : https;
      const req = protocol.request(options, (res) => {
        let data = '';
        res.on('data', (d) => { data += d; });
        res.on('end', () => {
          try {
            resolve({ status: res.statusCode, body: data ? JSON.parse(data) : {} });
          } catch (e) {
            resolve({ status: res.statusCode, body: data });
          }
        });
      });
      req.on('error', reject);
      if (body) req.write(JSON.stringify(body));
      req.end();
    });
  }

  async _createIssue(projectId, finding) {
    const encodedId = encodeURIComponent(projectId);
    const title = `[OmniGuard] ${finding.severity?.toUpperCase() || 'MEDIUM'} - ${finding.title || finding.rule_id}`;
    const description = [
      `## OmniGuard Security Finding`,
      `**Rule ID:** \`${finding.rule_id}\``,
      `**Severity:** ${finding.severity}`,
      `**File:** \`${finding.file_path}\` (Line ${finding.line_start})`,
      `**Evidence:** \`${finding.evidence || 'N/A'}\``,
      `**Clause Reference:** ${finding.clause_reference || 'ISO 27001 A.8.28'}`,
      ``,
      finding.description || 'Security violation detected by OmniGuard compliance scan.',
      ``,
      `> Auto-generated by [OmniGuard Security Platform](https://omniguard.io)`
    ].join('\n');

    const labels = ['security', 'omniguard', finding.severity || 'medium'].join(',');
    const result = await this._apiRequest('POST', `/projects/${encodedId}/issues`, {
      title,
      description,
      labels
    });
    console.log(`[GitLab] Issue created: ${result.body?.web_url || result.status}`);
    return result;
  }

  async _postMRNote(projectId, mrIid, finding) {
    const encodedId = encodeURIComponent(projectId);
    const note = [
      `## ⚠️ OmniGuard Security Alert`,
      `**Rule:** \`${finding.rule_id}\` | **Severity:** \`${finding.severity}\``,
      `**File:** \`${finding.file_path}:${finding.line_start}\``,
      `**Issue:** ${finding.title}`,
      finding.description ? `\n${finding.description}` : ''
    ].join('\n');

    const result = await this._apiRequest('POST', `/projects/${encodedId}/merge_requests/${mrIid}/notes`, {
      body: note
    });
    console.log(`[GitLab] MR note posted to MR !${mrIid}: ${result.status}`);
    return result;
  }
}

module.exports = new GitlabIntegration();
