'use strict';
const https = require('https');

/**
 * ServiceNow Integration — creates Incident or Security Incident records
 * from OmniGuard findings using the ServiceNow Table REST API.
 *
 * Required env / config:
 *   SERVICENOW_INSTANCE — ServiceNow instance name (e.g., "mycompany" for mycompany.service-now.com)
 *   SERVICENOW_USER     — API username (basic auth)
 *   SERVICENOW_PASSWORD — API password (basic auth)
 *   SERVICENOW_TABLE    — Table to write to (default: "sn_si_incident" for Security Incidents)
 */
class ServicenowIntegration {
  constructor() {
    this.instance = process.env.SERVICENOW_INSTANCE || '';
    this.user = process.env.SERVICENOW_USER || '';
    this.password = process.env.SERVICENOW_PASSWORD || '';
    this.table = process.env.SERVICENOW_TABLE || 'sn_si_incident';
  }

  async execute(payload = {}) {
    const { finding, table, action = 'create-incident' } = payload;

    if (!this.instance || !this.user || !this.password) {
      console.warn('[ServiceNow] SERVICENOW_INSTANCE / SERVICENOW_USER / SERVICENOW_PASSWORD not configured. Skipping.');
      return { skipped: true };
    }

    const targetTable = table || this.table;

    if (action === 'update' && payload.sysId) {
      return this._updateRecord(targetTable, payload.sysId, payload.updateData || {});
    }
    return this._createIncident(targetTable, finding);
  }

  _getAuthHeader() {
    return 'Basic ' + Buffer.from(`${this.user}:${this.password}`).toString('base64');
  }

  _apiRequest(method, path, body = null) {
    return new Promise((resolve, reject) => {
      const hostname = `${this.instance}.service-now.com`;
      const options = {
        hostname,
        port: 443,
        path: `/api/now/table${path}`,
        method,
        headers: {
          'Content-Type': 'application/json',
          'Accept': 'application/json',
          'Authorization': this._getAuthHeader()
        }
      };

      const req = https.request(options, (res) => {
        let data = '';
        res.on('data', (d) => { data += d; });
        res.on('end', () => {
          try {
            resolve({ status: res.statusCode, body: data ? JSON.parse(data) : {} });
          } catch (e) {
            resolve({ status: res.statusCode, body: data });
          }
        });
      });

      req.on('error', (err) => {
        console.error(`[ServiceNow] Request error: ${err.message}`);
        reject(err);
      });

      if (body) req.write(JSON.stringify(body));
      req.end();
    });
  }

  async _createIncident(table, finding) {
    // ServiceNow impact/urgency values: 1=High, 2=Medium, 3=Low
    const impactMap = { critical: '1', high: '1', medium: '2', low: '3' };
    const urgencyMap = { critical: '1', high: '2', medium: '2', low: '3' };

    const shortDescription = `[OmniGuard] ${(finding?.severity || 'medium').toUpperCase()} - ${finding?.title || finding?.rule_id || 'Security Violation'}`;
    const description = [
      `OmniGuard Security Finding`,
      `=`.repeat(40),
      `Rule ID: ${finding?.rule_id || 'N/A'}`,
      `Severity: ${finding?.severity || 'medium'}`,
      `File: ${finding?.file_path || 'N/A'} (Line ${finding?.line_start || 0})`,
      `Evidence: ${finding?.evidence || 'N/A'}`,
      `Compliance Clause: ${finding?.clause_reference || 'ISO 27001 A.8.28'}`,
      ``,
      `Description: ${finding?.description || 'Security violation detected by OmniGuard compliance scan.'}`,
      ``,
      finding?.ai_remediation ? `Suggested Remediation: ${finding.ai_remediation}` : '',
      ``,
      `Generated by OmniGuard Security Platform`
    ].filter((l) => l !== undefined).join('\n');

    const record = {
      short_description: shortDescription,
      description,
      category: 'software',
      subcategory: 'Security',
      impact: impactMap[finding?.severity] || '2',
      urgency: urgencyMap[finding?.severity] || '2',
      assignment_group: process.env.SERVICENOW_ASSIGNMENT_GROUP || 'Security Operations',
      cmdb_ci: finding?.file_path || '',
      work_notes: `Auto-created by OmniGuard AI Compliance Engine. Scan ID: ${finding?.scan_id || 'N/A'}`
    };

    const result = await this._apiRequest('POST', `/${table}`, record);

    if (result.status === 201) {
      const sysId = result.body?.result?.sys_id;
      const number = result.body?.result?.number;
      console.log(`[ServiceNow] Incident created: ${number} (sys_id: ${sysId})`);
    } else {
      console.warn(`[ServiceNow] Incident creation returned HTTP ${result.status}: ${JSON.stringify(result.body).substring(0, 200)}`);
    }

    return result;
  }

  async _updateRecord(table, sysId, updateData) {
    const result = await this._apiRequest('PATCH', `/${table}/${sysId}`, updateData);
    console.log(`[ServiceNow] Record ${sysId} updated: HTTP ${result.status}`);
    return result;
  }
}

module.exports = new ServicenowIntegration();
