const COMPLIANCE_RULES = [
  // ── SAST: Injection ──────────────────────────────────────────────────────
  { rule_id: 'SAST-INJ-001', category: 'sast', title: 'SQL Injection via String Concatenation', severity: 'critical', clause_reference: 'OWASP A03:2021 Injection, PCI DSS 6.2.4, ISO 27001 A.8.28', pattern: /(?:execute|query|raw|cursor\.execute)\s*\(\s*(?:f?["'`].*(?:\+|%s|\$\{|\{)|\w+\s*\+)/gi, extensions: ['.py', '.js', '.ts', '.rb', '.php', '.java'] },
  { rule_id: 'SAST-INJ-002', category: 'sast', title: 'NoSQL Injection Pattern', severity: 'critical', clause_reference: 'OWASP A03:2021, ISO 27001 A.8.28', pattern: /\$(?:where|ne|gt|lt|gte|lte|regex|in|nin|or|and|not|nor|exists|type|expr)\b/gi, extensions: ['.js', '.ts', '.py'] },
  { rule_id: 'SAST-INJ-003', category: 'sast', title: 'Command Injection via exec/spawn/system', severity: 'critical', clause_reference: 'OWASP A03:2021, NIST SP 800-53 SI-10', pattern: /(?:child_process|exec|execSync|spawn|spawnSync|system|popen|subprocess\.(?:call|run|Popen))\s*\([^)]*(?:req\.|input|argv|params|query|body)/gi, extensions: ['.js', '.ts', '.py', '.rb', '.php'] },
  { rule_id: 'SAST-INJ-004', category: 'sast', title: 'LDAP Injection', severity: 'high', clause_reference: 'OWASP A03:2021, ISO 27001 A.8.28', pattern: /(?:ldap_search|ldap_bind|ldap\.search)\s*\([^)]*(?:\+|%s|\$\{|format)/gi, extensions: ['.py', '.js', '.java', '.php'] },
  { rule_id: 'SAST-INJ-005', category: 'sast', title: 'XPath Injection', severity: 'high', clause_reference: 'OWASP A03:2021', pattern: /xpath\s*\([^)]*(?:\+|%s|\$\{)/gi, extensions: ['.py', '.js', '.java', '.php'] },
  { rule_id: 'SAST-INJ-006', category: 'sast', title: 'Template Injection (SSTI)', severity: 'critical', clause_reference: 'OWASP A03:2021, ISO 27001 A.8.28', pattern: /(?:render_template_string|Template\s*\(|Jinja2|eval\s*\(.*(?:request|input|params))/gi, extensions: ['.py', '.js', '.ts', '.rb'] },
  { rule_id: 'SAST-INJ-007', category: 'sast', title: 'Regex Injection (ReDoS)', severity: 'medium', clause_reference: 'OWASP A03:2021', pattern: /new\s+RegExp\s*\(\s*(?:req\.|input|params|query|body|argv)/gi, extensions: ['.js', '.ts'] },
  { rule_id: 'SAST-INJ-008', category: 'sast', title: 'Header Injection', severity: 'high', clause_reference: 'OWASP A03:2021', pattern: /(?:setHeader|writeHead|res\.set)\s*\([^)]*(?:req\.|input|params|query)/gi, extensions: ['.js', '.ts'] },

  // ── SAST: XSS ────────────────────────────────────────────────────────────
  { rule_id: 'SAST-XSS-001', category: 'sast', title: 'Cross-Site Scripting via innerHTML', severity: 'high', clause_reference: 'OWASP A07:2021, PCI DSS 6.2.4, SOC2 CC6.1', pattern: /\.innerHTML\s*=\s*(?!['"`]<)/gi, extensions: ['.js', '.ts', '.tsx', '.jsx', '.html'] },
  { rule_id: 'SAST-XSS-002', category: 'sast', title: 'XSS via document.write', severity: 'high', clause_reference: 'OWASP A07:2021', pattern: /document\.write\s*\(/gi, extensions: ['.js', '.ts', '.html'] },
  { rule_id: 'SAST-XSS-003', category: 'sast', title: 'XSS via dangerouslySetInnerHTML', severity: 'high', clause_reference: 'OWASP A07:2021, ISO 27001 A.8.28', pattern: /dangerouslySetInnerHTML/gi, extensions: ['.jsx', '.tsx', '.js', '.ts'] },
  { rule_id: 'SAST-XSS-004', category: 'sast', title: 'Unescaped Template Output', severity: 'medium', clause_reference: 'OWASP A07:2021', pattern: /\{\{\{.*\}\}\}|<%=.*%>|<%-.*%>/gi, extensions: ['.html', '.ejs', '.hbs', '.mustache'] },
  { rule_id: 'SAST-XSS-005', category: 'sast', title: 'DOM XSS via location/URL manipulation', severity: 'high', clause_reference: 'OWASP A07:2021', pattern: /(?:location\.hash|location\.search|window\.location|document\.URL|document\.referrer)\s*[^;]*(?:innerHTML|document\.write|eval)/gi, extensions: ['.js', '.ts'] },

  // ── SAST: Authentication & Session ────────────────────────────────────────
  { rule_id: 'SAST-AUTH-001', category: 'sast', title: 'Hardcoded Password', severity: 'critical', clause_reference: 'PCI DSS 8.3.6, ISO 27001 A.8.5, SOC2 CC6.1', pattern: /(?:password|passwd|pwd|secret|token|api_key|apikey|api_secret)\s*[:=]\s*['"][^'"]{4,}/gi, extensions: ['.js', '.ts', '.py', '.rb', '.java', '.php', '.yaml', '.yml', '.json', '.env', '.cfg', '.ini', '.conf', '.toml'] },
  { rule_id: 'SAST-AUTH-002', category: 'sast', title: 'Weak Password Comparison', severity: 'high', clause_reference: 'OWASP A07:2021, PCI DSS 8.3', pattern: /(?:password|passwd)\s*(?:===?|!==?|==)\s*(?:req\.|input|params|body)/gi, extensions: ['.js', '.ts', '.py', '.rb'] },
  { rule_id: 'SAST-AUTH-003', category: 'sast', title: 'Missing Authentication Check', severity: 'high', clause_reference: 'OWASP A07:2021, SOC2 CC6.1', pattern: /(?:app\.(?:get|post|put|delete|patch)|router\.(?:get|post|put|delete))\s*\(\s*['"][^'"]+['"]\s*,\s*(?:async\s+)?\(\s*req/gi, extensions: ['.js', '.ts'] },
  { rule_id: 'SAST-AUTH-004', category: 'sast', title: 'JWT Secret Hardcoded', severity: 'critical', clause_reference: 'PCI DSS 8.3.6, ISO 27001 A.8.5', pattern: /jwt\.sign\s*\([^)]*['"][^'"]{8,}['"]/gi, extensions: ['.js', '.ts'] },
  { rule_id: 'SAST-AUTH-005', category: 'sast', title: 'Session Cookie Without Secure Flag', severity: 'medium', clause_reference: 'OWASP A07:2021, PCI DSS 6.2.4', pattern: /(?:session|cookie).*(?:secure\s*:\s*false|httpOnly\s*:\s*false)/gi, extensions: ['.js', '.ts'] },
  { rule_id: 'SAST-AUTH-006', category: 'sast', title: 'OAuth State Parameter Missing', severity: 'medium', clause_reference: 'OWASP A07:2021', pattern: /oauth.*(?:redirect|callback)(?:(?!state).)*$/gim, extensions: ['.js', '.ts', '.py'] },

  // ── SAST: Cryptography ────────────────────────────────────────────────────
  { rule_id: 'SAST-CRYPTO-001', category: 'sast', title: 'Weak Hash Algorithm (MD5/SHA1)', severity: 'high', clause_reference: 'PCI DSS 4.2.2, ISO 27001 A.8.24, NIST SP 800-131A', pattern: /(?:md5|sha1|sha-1)\s*\(/gi, extensions: ['.js', '.ts', '.py', '.rb', '.java', '.php', '.go'] },
  { rule_id: 'SAST-CRYPTO-002', category: 'sast', title: 'Weak Encryption (DES/RC4/ECB)', severity: 'critical', clause_reference: 'PCI DSS 4.2.2, NIST SP 800-131A', pattern: /\b(?:DES|RC4|ECB|Blowfish|RC2)\b/gi, extensions: ['.js', '.ts', '.py', '.java', '.go'] },
  { rule_id: 'SAST-CRYPTO-003', category: 'sast', title: 'Hardcoded IV/Nonce', severity: 'high', clause_reference: 'PCI DSS 4.2.2, ISO 27001 A.8.24', pattern: /(?:iv|nonce|initialization.?vector)\s*[:=]\s*(?:['"][^'"]+['"]|Buffer\.from|b')/gi, extensions: ['.js', '.ts', '.py', '.java'] },
  { rule_id: 'SAST-CRYPTO-004', category: 'sast', title: 'Insufficient Key Length', severity: 'high', clause_reference: 'PCI DSS 4.2.2, NIST SP 800-57', pattern: /(?:key.?(?:size|length|bits))\s*[:=]\s*(?:64|56|40|128)\b/gi, extensions: ['.js', '.ts', '.py', '.java'] },
  { rule_id: 'SAST-CRYPTO-005', category: 'sast', title: 'Math.random Used for Security', severity: 'high', clause_reference: 'OWASP A02:2021, ISO 27001 A.8.24', pattern: /Math\.random\s*\(\)/g, extensions: ['.js', '.ts'] },
  { rule_id: 'SAST-CRYPTO-006', category: 'sast', title: 'TLS/SSL Verification Disabled', severity: 'critical', clause_reference: 'PCI DSS 4.2.1, ISO 27001 A.8.24', pattern: /(?:rejectUnauthorized\s*:\s*false|verify\s*[:=]\s*false|CERT_NONE|InsecureSkipVerify|ssl_verify.*false)/gi, extensions: ['.js', '.ts', '.py', '.go', '.rb', '.java'] },

  // ── SAST: Secrets & Credentials ───────────────────────────────────────────
  { rule_id: 'SAST-SEC-001', category: 'sast', title: 'AWS Access Key Exposed', severity: 'critical', clause_reference: 'PCI DSS 8.3.6, SOC2 CC6.1, ISO 27001 A.8.5', pattern: /(?:AKIA|ASIA)[A-Z0-9]{16}/g, extensions: null },
  { rule_id: 'SAST-SEC-002', category: 'sast', title: 'GitHub Token Exposed', severity: 'critical', clause_reference: 'PCI DSS 8.3.6, SOC2 CC6.1', pattern: /gh[pousr]_[A-Za-z0-9_]{36,}/g, extensions: null },
  { rule_id: 'SAST-SEC-003', category: 'sast', title: 'Private Key in Source', severity: 'critical', clause_reference: 'PCI DSS 3.4.1, ISO 27001 A.8.5', pattern: /-----BEGIN (?:RSA |EC |DSA |OPENSSH )?PRIVATE KEY-----/g, extensions: null },
  { rule_id: 'SAST-SEC-004', category: 'sast', title: 'Generic API Key Pattern', severity: 'high', clause_reference: 'PCI DSS 8.3.6, SOC2 CC6.1', pattern: /(?:api[_-]?key|apikey|api[_-]?secret)\s*[:=]\s*['"][A-Za-z0-9+/=_-]{20,}['"]/gi, extensions: null },
  { rule_id: 'SAST-SEC-005', category: 'sast', title: 'Database Connection String with Password', severity: 'critical', clause_reference: 'PCI DSS 8.3.6, ISO 27001 A.8.5', pattern: /(?:postgres|mysql|mongodb|redis|amqp):\/\/[^:]+:[^@]+@/gi, extensions: null },
  { rule_id: 'SAST-SEC-006', category: 'sast', title: 'Slack/Discord Webhook URL', severity: 'high', clause_reference: 'SOC2 CC6.1', pattern: /https:\/\/(?:hooks\.slack\.com\/services|discord(?:app)?\.com\/api\/webhooks)\/[^\s'"]+/gi, extensions: null },
  { rule_id: 'SAST-SEC-007', category: 'sast', title: 'Google API Key', severity: 'high', clause_reference: 'PCI DSS 8.3.6', pattern: /AIza[A-Za-z0-9_-]{35}/g, extensions: null },
  { rule_id: 'SAST-SEC-008', category: 'sast', title: 'Stripe Secret Key', severity: 'critical', clause_reference: 'PCI DSS 8.3.6, 3.4.1', pattern: /sk_live_[A-Za-z0-9]{20,}/g, extensions: null },
  { rule_id: 'SAST-SEC-009', category: 'sast', title: 'Twilio Auth Token', severity: 'high', clause_reference: 'PCI DSS 8.3.6', pattern: /(?:twilio|TWILIO).*(?:auth.?token|AUTH.?TOKEN)\s*[:=]\s*['"][a-f0-9]{32}['"]/gi, extensions: null },
  { rule_id: 'SAST-SEC-010', category: 'sast', title: 'SendGrid API Key', severity: 'high', clause_reference: 'PCI DSS 8.3.6', pattern: /SG\.[A-Za-z0-9_-]{22}\.[A-Za-z0-9_-]{43}/g, extensions: null },

  // ── SAST: Deserialization ─────────────────────────────────────────────────
  { rule_id: 'SAST-DESER-001', category: 'sast', title: 'Unsafe Deserialization (pickle/yaml)', severity: 'critical', clause_reference: 'OWASP A08:2021, ISO 27001 A.8.28', pattern: /(?:pickle\.loads?|yaml\.(?:load|unsafe_load)|Marshal\.load|unserialize|ObjectInputStream)/gi, extensions: ['.py', '.rb', '.java', '.php'] },
  { rule_id: 'SAST-DESER-002', category: 'sast', title: 'Unsafe JSON Parsing with eval', severity: 'critical', clause_reference: 'OWASP A08:2021', pattern: /eval\s*\(\s*(?:req\.|request\.|input|params|body|data|json)/gi, extensions: ['.js', '.ts', '.py'] },

  // ── SAST: Path Traversal & File ───────────────────────────────────────────
  { rule_id: 'SAST-PATH-001', category: 'sast', title: 'Path Traversal via User Input', severity: 'high', clause_reference: 'OWASP A01:2021, PCI DSS 6.2.4', pattern: /(?:readFile|writeFile|createReadStream|createWriteStream|open|access)\s*\([^)]*(?:req\.|params|query|body|input|argv)/gi, extensions: ['.js', '.ts'] },
  { rule_id: 'SAST-PATH-002', category: 'sast', title: 'Python Path Traversal', severity: 'high', clause_reference: 'OWASP A01:2021', pattern: /open\s*\([^)]*(?:request\.|input|argv|sys\.argv)/gi, extensions: ['.py'] },
  { rule_id: 'SAST-PATH-003', category: 'sast', title: 'Unrestricted File Upload', severity: 'high', clause_reference: 'OWASP A04:2021, PCI DSS 6.2.4', pattern: /(?:multer|upload|formidable|busboy)(?:(?!fileFilter|limits|allowedMime).){0,200}$/gim, extensions: ['.js', '.ts'] },

  // ── SAST: Error Handling & Logging ────────────────────────────────────────
  { rule_id: 'SAST-ERR-001', category: 'sast', title: 'Stack Trace Exposed to Client', severity: 'medium', clause_reference: 'OWASP A09:2021, PCI DSS 6.2.4', pattern: /(?:res\.(?:send|json|end))\s*\([^)]*(?:err\.stack|error\.stack|e\.stack)/gi, extensions: ['.js', '.ts'] },
  { rule_id: 'SAST-ERR-002', category: 'sast', title: 'Empty Catch Block', severity: 'low', clause_reference: 'ISO 27001 A.8.28, SOC2 CC7.2', pattern: /catch\s*\([^)]*\)\s*\{\s*\}/g, extensions: ['.js', '.ts', '.java'] },
  { rule_id: 'SAST-ERR-003', category: 'sast', title: 'Console.log in Production Code', severity: 'low', clause_reference: 'ISO 27001 A.8.28', pattern: /console\.log\s*\(/g, extensions: ['.js', '.ts', '.tsx', '.jsx'] },
  { rule_id: 'SAST-ERR-004', category: 'sast', title: 'Debug Mode Enabled', severity: 'medium', clause_reference: 'PCI DSS 6.2.4, ISO 27001 A.8.28', pattern: /(?:DEBUG\s*[:=]\s*(?:true|1|['"]true['"])|app\.debug\s*=\s*True|FLASK_DEBUG|DJANGO_DEBUG)/gi, extensions: null },

  // ── SAST: CSRF ────────────────────────────────────────────────────────────
  { rule_id: 'SAST-CSRF-001', category: 'sast', title: 'Missing CSRF Protection', severity: 'high', clause_reference: 'OWASP A01:2021, PCI DSS 6.2.4', pattern: /(?:csrf|csrfProtection)\s*[:=]\s*false/gi, extensions: ['.js', '.ts', '.py'] },
  { rule_id: 'SAST-CSRF-002', category: 'sast', title: 'CORS Wildcard Origin', severity: 'high', clause_reference: 'OWASP A01:2021, SOC2 CC6.6', pattern: /(?:Access-Control-Allow-Origin|origin)\s*[:=]\s*['"]\*['"]/gi, extensions: ['.js', '.ts', '.py', '.java', '.conf'] },

  // ── SAST: Insecure Dependencies ───────────────────────────────────────────
  { rule_id: 'SAST-DEP-001', category: 'sast', title: 'Known Vulnerable Dependency (lodash <4.17.21)', severity: 'high', clause_reference: 'PCI DSS 6.3.2, NIST SP 800-53 RA-5', pattern: /"lodash"\s*:\s*"[^"]*(?:[0-3]\.|4\.(?:[0-9]|1[0-6]|17\.(?:[0-9]|1[0-9]|20)))\./g, extensions: ['.json'] },
  { rule_id: 'SAST-DEP-002', category: 'sast', title: 'Known Vulnerable Dependency (log4j)', severity: 'critical', clause_reference: 'PCI DSS 6.3.2, NIST SP 800-53 RA-5', pattern: /log4j.*(?:2\.(?:[0-9]|1[0-4])\.[0-9])/gi, extensions: ['.xml', '.gradle', '.json', '.toml'] },
  { rule_id: 'SAST-DEP-003', category: 'sast', title: 'Dependency with No Lockfile', severity: 'medium', clause_reference: 'PCI DSS 6.3, ISO 27001 A.8.28', pattern: /(?:npm install|pip install|gem install)(?:(?!--frozen|--ci|--lock).)*$/gim, extensions: ['.sh', '.yml', '.yaml'] },

  // ── SAST: Miscellaneous ───────────────────────────────────────────────────
  { rule_id: 'SAST-MISC-001', category: 'sast', title: 'Eval() Usage', severity: 'critical', clause_reference: 'OWASP A03:2021, ISO 27001 A.8.28', pattern: /\beval\s*\(\s*(?!['"`](?:strict|use strict))/gi, extensions: ['.js', '.ts', '.py'] },
  { rule_id: 'SAST-MISC-002', category: 'sast', title: 'setTimeout/setInterval with String Argument', severity: 'high', clause_reference: 'OWASP A03:2021', pattern: /(?:setTimeout|setInterval)\s*\(\s*['"`]/gi, extensions: ['.js', '.ts'] },
  { rule_id: 'SAST-MISC-003', category: 'sast', title: 'Prototype Pollution Risk', severity: 'high', clause_reference: 'OWASP A08:2021', pattern: /(?:__proto__|constructor\.prototype|Object\.assign\s*\(\s*\{\})/gi, extensions: ['.js', '.ts'] },
  { rule_id: 'SAST-MISC-004', category: 'sast', title: 'Unrestricted Redirect', severity: 'medium', clause_reference: 'OWASP A01:2021', pattern: /(?:res\.redirect|redirect)\s*\(\s*(?:req\.|params|query|body)/gi, extensions: ['.js', '.ts', '.py'] },
  { rule_id: 'SAST-MISC-005', category: 'sast', title: 'Race Condition (TOCTOU)', severity: 'medium', clause_reference: 'ISO 27001 A.8.28', pattern: /(?:fs\.existsSync|os\.path\.exists)\s*\([^)]+\)[\s\S]{0,100}(?:fs\.readFileSync|open\s*\()/gi, extensions: ['.js', '.ts', '.py'] },
  { rule_id: 'SAST-MISC-006', category: 'sast', title: 'Unsafe Regular Expression', severity: 'medium', clause_reference: 'OWASP A03:2021', pattern: /new\s+RegExp\s*\(\s*['"][^'"]*(?:\+\*|\*\+|\{\d+,\}.*\{\d+,\})/gi, extensions: ['.js', '.ts'] },

  // ── DAST: HTTP Security Headers ───────────────────────────────────────────
  { rule_id: 'DAST-HDR-001', category: 'dast', title: 'Missing Content-Security-Policy Header', severity: 'medium', clause_reference: 'OWASP A05:2021, PCI DSS 6.4.1, SOC2 CC6.6', pattern: /(?:helmet|csp|content-security-policy)/gi, negate: true, fileLevel: true, extensions: ['.js', '.ts'] },
  { rule_id: 'DAST-HDR-002', category: 'dast', title: 'Missing X-Frame-Options', severity: 'medium', clause_reference: 'OWASP A05:2021', pattern: /x-frame-options/gi, negate: true, fileLevel: true, extensions: ['.js', '.ts'] },
  { rule_id: 'DAST-HDR-003', category: 'dast', title: 'Missing Strict-Transport-Security', severity: 'medium', clause_reference: 'PCI DSS 4.2.1, NIST SP 800-52', pattern: /strict-transport-security/gi, negate: true, fileLevel: true, extensions: ['.js', '.ts'] },
  { rule_id: 'DAST-HDR-004', category: 'dast', title: 'Missing X-Content-Type-Options', severity: 'low', clause_reference: 'OWASP A05:2021', pattern: /x-content-type-options/gi, negate: true, fileLevel: true, extensions: ['.js', '.ts'] },
  { rule_id: 'DAST-HDR-005', category: 'dast', title: 'HTTP Used Instead of HTTPS', severity: 'high', clause_reference: 'PCI DSS 4.2.1, ISO 27001 A.8.24', pattern: /http:\/\/(?!localhost|127\.0\.0\.1|0\.0\.0\.0|::1)/gi, extensions: ['.js', '.ts', '.py', '.yaml', '.yml', '.json', '.env'] },

  // ── DAST: Authentication Config ───────────────────────────────────────────
  { rule_id: 'DAST-AUTH-001', category: 'dast', title: 'Rate Limiting Not Configured', severity: 'medium', clause_reference: 'OWASP A04:2021, PCI DSS 6.2.4', pattern: /(?:rate.?limit|express-rate-limit|rateLimit)/gi, negate: true, fileLevel: true, extensions: ['.js', '.ts'] },
  { rule_id: 'DAST-AUTH-002', category: 'dast', title: 'HTTPS Redirect Not Enforced', severity: 'high', clause_reference: 'PCI DSS 4.2.1', pattern: /(?:force.?ssl|redirect.*https|requireHTTPS)/gi, negate: true, fileLevel: true, extensions: ['.js', '.ts'] },

  // ── PCI DSS v4.0 ─────────────────────────────────────────────────────────
  { rule_id: 'PCI-DSS-1.2.5', category: 'pci', title: 'Network Segmentation: Open Ports in Config', severity: 'high', clause_reference: 'PCI DSS v4.0 Req 1.2.5: Restrict ports/protocols to business need', pattern: /(?:port|listen)\s*[:=]\s*(?:0|21|23|25|53|110|135|139|445|3389|5900)\b/gi, extensions: null },
  { rule_id: 'PCI-DSS-2.2.1', category: 'pci', title: 'Default Credentials Not Changed', severity: 'critical', clause_reference: 'PCI DSS v4.0 Req 2.2.1: Change defaults before deployment', pattern: /(?:admin|root|test|guest|default)\s*[:=]\s*['"](?:admin|password|123456|root|test|guest|default)['"]/gi, extensions: null },
  { rule_id: 'PCI-DSS-3.4.1', category: 'pci', title: 'Cardholder Data Not Encrypted at Rest', severity: 'critical', clause_reference: 'PCI DSS v4.0 Req 3.4.1: Render PAN unreadable anywhere it is stored', pattern: /(?:card.?number|pan|credit.?card|cc.?num)\s*[:=]\s*['"][0-9]{13,19}['"]/gi, extensions: null },
  { rule_id: 'PCI-DSS-3.5.1', category: 'pci', title: 'Cleartext PAN in Logs', severity: 'critical', clause_reference: 'PCI DSS v4.0 Req 3.5.1: PAN secured if stored', pattern: /(?:log|console|print|logger).*(?:card.?number|pan|credit.?card|cc.?num)/gi, extensions: null },
  { rule_id: 'PCI-DSS-4.2.1', category: 'pci', title: 'Unencrypted Transmission of Sensitive Data', severity: 'critical', clause_reference: 'PCI DSS v4.0 Req 4.2.1: Strong cryptography for PAN transmission', pattern: /http:\/\/[^'"]*(?:payment|card|checkout|billing|transaction)/gi, extensions: null },
  { rule_id: 'PCI-DSS-6.2.4a', category: 'pci', title: 'Software Attack Surface: Eval Usage', severity: 'critical', clause_reference: 'PCI DSS v4.0 Req 6.2.4: Prevent common software attacks', pattern: /\beval\s*\(/gi, extensions: ['.js', '.ts', '.py'] },
  { rule_id: 'PCI-DSS-6.3.1', category: 'pci', title: 'Missing Security Patch Process', severity: 'medium', clause_reference: 'PCI DSS v4.0 Req 6.3.1: Identify and manage vulnerabilities', pattern: /TODO.*(?:update|upgrade|patch|vulnerability|CVE)/gi, extensions: null },
  { rule_id: 'PCI-DSS-6.4.1', category: 'pci', title: 'Missing WAF/CSP Configuration', severity: 'high', clause_reference: 'PCI DSS v4.0 Req 6.4.1: Web application firewall for public apps', pattern: /(?:waf|firewall|cloudflare|cloudfront|content.security.policy)/gi, negate: true, fileLevel: true, extensions: ['.js', '.ts', '.yaml', '.yml', '.json'] },
  { rule_id: 'PCI-DSS-8.2.3', category: 'pci', title: 'No Password Complexity Enforcement', severity: 'medium', clause_reference: 'PCI DSS v4.0 Req 8.2.3: Strong authentication factors', pattern: /(?:password.?(?:length|min|max|policy|complexity|strength|regex))/gi, negate: true, fileLevel: true, extensions: ['.js', '.ts', '.py'] },
  { rule_id: 'PCI-DSS-8.3.6', category: 'pci', title: 'Hardcoded Credential in Application', severity: 'critical', clause_reference: 'PCI DSS v4.0 Req 8.3.6: Password not hardcoded in scripts', pattern: /(?:password|secret|token|key)\s*[:=]\s*['"][a-zA-Z0-9+/=_-]{8,}['"]/gi, extensions: null },
  { rule_id: 'PCI-DSS-10.2.1', category: 'pci', title: 'Missing Audit Logging', severity: 'high', clause_reference: 'PCI DSS v4.0 Req 10.2.1: Audit logs for user actions', pattern: /(?:audit.?log|event.?log|access.?log|security.?log)/gi, negate: true, fileLevel: true, extensions: ['.js', '.ts', '.py'] },
  { rule_id: 'PCI-DSS-11.3.1', category: 'pci', title: 'No Vulnerability Scanning Configured', severity: 'medium', clause_reference: 'PCI DSS v4.0 Req 11.3.1: Internal vulnerability scans', pattern: /(?:vuln.?scan|security.?scan|pentest|penetration.?test)/gi, negate: true, fileLevel: true, extensions: ['.yml', '.yaml', '.json'] },
  { rule_id: 'PCI-DSS-12.6.2', category: 'pci', title: 'No Security Awareness Documented', severity: 'low', clause_reference: 'PCI DSS v4.0 Req 12.6.2: Security awareness program', pattern: /(?:security.?training|security.?awareness)/gi, negate: true, fileLevel: true, extensions: ['.md', '.txt'] },

  // ── ISO 27001:2022 ────────────────────────────────────────────────────────
  { rule_id: 'ISO-27001-A.5.1', category: 'iso', title: 'Missing Security Policy Documentation', severity: 'medium', clause_reference: 'ISO 27001:2022 A.5.1: Information security policies', pattern: /(?:SECURITY\.md|security.?policy|information.?security)/gi, negate: true, fileLevel: true, extensions: ['.md', '.txt', '.rst'] },
  { rule_id: 'ISO-27001-A.8.3', category: 'iso', title: 'Unprotected Access to Sensitive Data', severity: 'high', clause_reference: 'ISO 27001:2022 A.8.3: Restriction of access to information', pattern: /(?:fs\.readFileSync|open)\s*\(\s*['"][^'"]*(?:\.env|\.key|\.pem|\.crt|password|secret|credentials)/gi, extensions: null },
  { rule_id: 'ISO-27001-A.8.5', category: 'iso', title: 'Improper Authentication Mechanism', severity: 'high', clause_reference: 'ISO 27001:2022 A.8.5: Secure authentication', pattern: /(?:basic.?auth|Basic\s+[A-Za-z0-9+/=]+)/gi, extensions: ['.js', '.ts', '.py'] },
  { rule_id: 'ISO-27001-A.8.9', category: 'iso', title: 'Configuration Not Externalized', severity: 'medium', clause_reference: 'ISO 27001:2022 A.8.9: Configuration management', pattern: /(?:host|port|database|db_name|endpoint)\s*[:=]\s*['"][^'"]+['"]/gi, extensions: ['.js', '.ts', '.py'] },
  { rule_id: 'ISO-27001-A.8.10', category: 'iso', title: 'Information Deletion Not Implemented', severity: 'medium', clause_reference: 'ISO 27001:2022 A.8.10: Information deletion', pattern: /(?:delete.*user|remove.*account|data.*retention|purge|gdpr.*delete)/gi, negate: true, fileLevel: true, extensions: ['.js', '.ts', '.py'] },
  { rule_id: 'ISO-27001-A.8.11', category: 'iso', title: 'Data Masking Not Applied', severity: 'medium', clause_reference: 'ISO 27001:2022 A.8.11: Data masking', pattern: /(?:mask|redact|anonymize|pseudonymize)/gi, negate: true, fileLevel: true, extensions: ['.js', '.ts', '.py'] },
  { rule_id: 'ISO-27001-A.8.12', category: 'iso', title: 'Data Leakage Prevention Missing', severity: 'high', clause_reference: 'ISO 27001:2022 A.8.12: Data leakage prevention', pattern: /(?:dlp|data.?loss|data.?leak|exfiltration)/gi, negate: true, fileLevel: true, extensions: ['.js', '.ts', '.py', '.yaml'] },
  { rule_id: 'ISO-27001-A.8.16', category: 'iso', title: 'Monitoring Activity Not Configured', severity: 'medium', clause_reference: 'ISO 27001:2022 A.8.16: Monitoring activities', pattern: /(?:monitor|alert|watchdog|health.?check|uptime)/gi, negate: true, fileLevel: true, extensions: ['.js', '.ts', '.yaml', '.yml'] },
  { rule_id: 'ISO-27001-A.8.23', category: 'iso', title: 'Web Filtering Not Enforced', severity: 'low', clause_reference: 'ISO 27001:2022 A.8.23: Web filtering', pattern: /(?:web.?filter|url.?filter|content.?filter|proxy)/gi, negate: true, fileLevel: true, extensions: ['.js', '.ts', '.yaml'] },
  { rule_id: 'ISO-27001-A.8.24', category: 'iso', title: 'Cryptography Usage Not Following Standards', severity: 'high', clause_reference: 'ISO 27001:2022 A.8.24: Use of cryptography', pattern: /(?:createCipher\b|Cipher\s*\(|crypto\.cipher)/gi, extensions: ['.js', '.ts', '.py'] },
  { rule_id: 'ISO-27001-A.8.25', category: 'iso', title: 'Missing Secure Development Lifecycle', severity: 'medium', clause_reference: 'ISO 27001:2022 A.8.25: Secure development life cycle', pattern: /(?:sdlc|secure.?development|code.?review|security.?review)/gi, negate: true, fileLevel: true, extensions: ['.md', '.yaml', '.yml'] },
  { rule_id: 'ISO-27001-A.8.26', category: 'iso', title: 'Application Security Requirements Missing', severity: 'medium', clause_reference: 'ISO 27001:2022 A.8.26: Application security requirements', pattern: /(?:security.?requirements|threat.?model|risk.?assessment)/gi, negate: true, fileLevel: true, extensions: ['.md', '.txt'] },
  { rule_id: 'ISO-27001-A.8.28', category: 'iso', title: 'Secure Coding Practices Not Followed', severity: 'high', clause_reference: 'ISO 27001:2022 A.8.28: Secure coding', pattern: /(?:TODO|FIXME|HACK|XXX|SECURITY|VULN|BUG).*(?:fix|patch|update|insecure|unsafe|vulnerable)/gi, extensions: null },
  { rule_id: 'ISO-27001-A.8.33', category: 'iso', title: 'Test Data Contains Production Information', severity: 'high', clause_reference: 'ISO 27001:2022 A.8.33: Test information', pattern: /(?:test|spec|__test__|_test).*(?:production|prod|real|live).*(?:key|token|password|secret)/gi, extensions: null },

  // ── SOC 2 ─────────────────────────────────────────────────────────────────
  { rule_id: 'SOC2-CC6.1-001', category: 'soc2', title: 'Logical Access Control Missing', severity: 'high', clause_reference: 'SOC 2 CC6.1: Logical and physical access controls', pattern: /(?:middleware|auth.?guard|authenticate|authorize|isAuthenticated|requireAuth)/gi, negate: true, fileLevel: true, extensions: ['.js', '.ts'] },
  { rule_id: 'SOC2-CC6.1-002', category: 'soc2', title: 'Role-Based Access Not Implemented', severity: 'high', clause_reference: 'SOC 2 CC6.1: Role-based access control', pattern: /(?:rbac|role.?based|permission.?check|hasRole|isAdmin|canAccess)/gi, negate: true, fileLevel: true, extensions: ['.js', '.ts', '.py'] },
  { rule_id: 'SOC2-CC6.2-001', category: 'soc2', title: 'Threat Detection Not Configured', severity: 'high', clause_reference: 'SOC 2 CC6.2: Threat and vulnerability management', pattern: /(?:intrusion|ids|ips|threat.?detect|anomaly.?detect|siem)/gi, negate: true, fileLevel: true, extensions: ['.js', '.ts', '.yaml', '.yml'] },
  { rule_id: 'SOC2-CC6.3-001', category: 'soc2', title: 'User Registration Without Verification', severity: 'medium', clause_reference: 'SOC 2 CC6.3: Registration and authorization', pattern: /(?:signup|register|create.?user|create.?account)(?:(?!verify|confirm|email|otp|captcha).)*$/gim, extensions: ['.js', '.ts', '.py'] },
  { rule_id: 'SOC2-CC6.6-001', category: 'soc2', title: 'Input Validation Missing', severity: 'high', clause_reference: 'SOC 2 CC6.6: System boundary protection', pattern: /(?:validate|sanitize|escape|purify|xss.?clean)/gi, negate: true, fileLevel: true, extensions: ['.js', '.ts'] },
  { rule_id: 'SOC2-CC6.7-001', category: 'soc2', title: 'Data Transmission Not Encrypted', severity: 'high', clause_reference: 'SOC 2 CC6.7: Restrict data movement', pattern: /http:\/\/(?!localhost|127|0\.0|::1)/gi, extensions: null },
  { rule_id: 'SOC2-CC6.8-001', category: 'soc2', title: 'Unauthorized Software Prevention Missing', severity: 'medium', clause_reference: 'SOC 2 CC6.8: Prevent unauthorized software', pattern: /(?:whitelist|allowlist|approved.?software|package.?lock)/gi, negate: true, fileLevel: true, extensions: ['.json', '.yaml', '.yml'] },
  { rule_id: 'SOC2-CC7.1-001', category: 'soc2', title: 'Missing Incident Detection Mechanism', severity: 'high', clause_reference: 'SOC 2 CC7.1: Detect and report deviations', pattern: /(?:incident|alert|notification|pagerduty|opsgenie|statuspage)/gi, negate: true, fileLevel: true, extensions: ['.js', '.ts', '.yaml', '.yml'] },
  { rule_id: 'SOC2-CC7.2-001', category: 'soc2', title: 'Anomaly Monitoring Not Implemented', severity: 'medium', clause_reference: 'SOC 2 CC7.2: Monitor system components for anomalies', pattern: /(?:anomaly|baseline|threshold|sla.?monitor|uptime.?check)/gi, negate: true, fileLevel: true, extensions: ['.js', '.ts', '.yaml'] },
  { rule_id: 'SOC2-CC7.3-001', category: 'soc2', title: 'Incident Response Plan Missing', severity: 'medium', clause_reference: 'SOC 2 CC7.3: Evaluate detected events', pattern: /(?:incident.?response|runbook|playbook|escalation)/gi, negate: true, fileLevel: true, extensions: ['.md', '.yaml', '.yml'] },
  { rule_id: 'SOC2-CC8.1-001', category: 'soc2', title: 'Change Management Process Missing', severity: 'medium', clause_reference: 'SOC 2 CC8.1: Authorize, design, test changes', pattern: /(?:change.?management|change.?control|approval.?process|change.?log)/gi, negate: true, fileLevel: true, extensions: ['.md', '.yaml', '.yml'] },

  // ── HIPAA ─────────────────────────────────────────────────────────────────
  { rule_id: 'HIPAA-164.312a', category: 'hipaa', title: 'Missing Unique User Identification', severity: 'high', clause_reference: 'HIPAA §164.312(a)(2)(i): Unique user identification', pattern: /(?:unique.?user|user.?id|identity.?provider|authentication)/gi, negate: true, fileLevel: true, extensions: ['.js', '.ts', '.py'] },
  { rule_id: 'HIPAA-164.312a-2', category: 'hipaa', title: 'Emergency Access Procedure Not Defined', severity: 'medium', clause_reference: 'HIPAA §164.312(a)(2)(ii): Emergency access procedure', pattern: /(?:emergency.?access|break.?glass|override.?auth)/gi, negate: true, fileLevel: true, extensions: ['.md', '.js', '.ts'] },
  { rule_id: 'HIPAA-164.312a-3', category: 'hipaa', title: 'Auto Logoff Not Implemented', severity: 'medium', clause_reference: 'HIPAA §164.312(a)(2)(iii): Automatic logoff', pattern: /(?:auto.?logoff|session.?timeout|idle.?timeout|session.?expire)/gi, negate: true, fileLevel: true, extensions: ['.js', '.ts'] },
  { rule_id: 'HIPAA-164.312a-4', category: 'hipaa', title: 'Data Encryption at Rest Missing', severity: 'critical', clause_reference: 'HIPAA §164.312(a)(2)(iv): Encryption and decryption', pattern: /(?:encrypt.?at.?rest|aes|encryption.?key|kms|aws.?kms|vault)/gi, negate: true, fileLevel: true, extensions: ['.js', '.ts', '.py', '.yaml'] },
  { rule_id: 'HIPAA-164.312b', category: 'hipaa', title: 'Audit Controls Not Implemented', severity: 'high', clause_reference: 'HIPAA §164.312(b): Audit controls', pattern: /(?:audit.?trail|audit.?log|access.?log|activity.?log)/gi, negate: true, fileLevel: true, extensions: ['.js', '.ts', '.py'] },
  { rule_id: 'HIPAA-164.312c-1', category: 'hipaa', title: 'Data Integrity Controls Missing', severity: 'high', clause_reference: 'HIPAA §164.312(c)(1): Integrity - authenticate ePHI', pattern: /(?:integrity.?check|checksum|hash.?verify|digital.?signature|hmac)/gi, negate: true, fileLevel: true, extensions: ['.js', '.ts', '.py'] },
  { rule_id: 'HIPAA-164.312c-2', category: 'hipaa', title: 'Mechanism to Authenticate ePHI Missing', severity: 'high', clause_reference: 'HIPAA §164.312(c)(2): Mechanism to authenticate electronic PHI', pattern: /(?:phi|protected.?health|patient.?data|medical.?record|health.?info)/gi, extensions: ['.js', '.ts', '.py', '.java'] },
  { rule_id: 'HIPAA-164.312d', category: 'hipaa', title: 'Person/Entity Authentication Missing', severity: 'high', clause_reference: 'HIPAA §164.312(d): Person or entity authentication', pattern: /(?:mfa|multi.?factor|two.?factor|2fa|totp|authenticator)/gi, negate: true, fileLevel: true, extensions: ['.js', '.ts', '.py'] },
  { rule_id: 'HIPAA-164.312e-1', category: 'hipaa', title: 'Transmission Security Missing', severity: 'critical', clause_reference: 'HIPAA §164.312(e)(1): Transmission security', pattern: /(?:tls|ssl|https|encryption.?in.?transit)/gi, negate: true, fileLevel: true, extensions: ['.js', '.ts', '.py', '.yaml'] },
  { rule_id: 'HIPAA-164.312e-2', category: 'hipaa', title: 'Encryption for Transmission Not Configured', severity: 'critical', clause_reference: 'HIPAA §164.312(e)(2)(ii): Encryption for transmission', pattern: /(?:tlsVersion|ssl.?version|cipher.?suite|tls.?config)/gi, negate: true, fileLevel: true, extensions: ['.js', '.ts', '.yaml'] },

  // ── NIST Cybersecurity Framework (CSF) ────────────────────────────────────
  { rule_id: 'NIST-ID.AM-1', category: 'nist', title: 'Asset Inventory Not Maintained', severity: 'medium', clause_reference: 'NIST CSF ID.AM-1: Physical devices and systems inventoried', pattern: /(?:asset.?inventory|cmdb|configuration.?management.?database)/gi, negate: true, fileLevel: true, extensions: ['.md', '.yaml', '.yml', '.json'] },
  { rule_id: 'NIST-ID.AM-2', category: 'nist', title: 'Software Inventory Not Maintained', severity: 'medium', clause_reference: 'NIST CSF ID.AM-2: Software platforms and applications inventoried', pattern: /(?:sbom|software.?bill.?of.?materials|dependency.?list|software.?inventory)/gi, negate: true, fileLevel: true, extensions: ['.md', '.yaml', '.json'] },
  { rule_id: 'NIST-ID.RA-1', category: 'nist', title: 'Risk Assessment Not Documented', severity: 'medium', clause_reference: 'NIST CSF ID.RA-1: Asset vulnerabilities identified and documented', pattern: /(?:risk.?assessment|threat.?model|vulnerability.?assessment)/gi, negate: true, fileLevel: true, extensions: ['.md', '.txt'] },
  { rule_id: 'NIST-PR.AC-1', category: 'nist', title: 'Identity Management Missing', severity: 'high', clause_reference: 'NIST CSF PR.AC-1: Identities and credentials managed', pattern: /(?:identity.?management|iam|identity.?provider|ldap|saml|oidc)/gi, negate: true, fileLevel: true, extensions: ['.js', '.ts', '.yaml'] },
  { rule_id: 'NIST-PR.AC-4', category: 'nist', title: 'Access Permissions Not Managed', severity: 'high', clause_reference: 'NIST CSF PR.AC-4: Access permissions managed (least privilege)', pattern: /(?:least.?privilege|rbac|abac|permission|access.?control.?list)/gi, negate: true, fileLevel: true, extensions: ['.js', '.ts', '.py'] },
  { rule_id: 'NIST-PR.AC-7', category: 'nist', title: 'No User/Device Authentication', severity: 'high', clause_reference: 'NIST CSF PR.AC-7: Users, devices, and assets authenticated', pattern: /(?:authenticate|auth.?middleware|verify.?token|session.?check)/gi, negate: true, fileLevel: true, extensions: ['.js', '.ts'] },
  { rule_id: 'NIST-PR.DS-1', category: 'nist', title: 'Data-at-Rest Protection Missing', severity: 'high', clause_reference: 'NIST CSF PR.DS-1: Data-at-rest is protected', pattern: /(?:encrypt.?at.?rest|disk.?encryption|database.?encryption|transparent.?data)/gi, negate: true, fileLevel: true, extensions: ['.js', '.ts', '.py', '.yaml'] },
  { rule_id: 'NIST-PR.DS-2', category: 'nist', title: 'Data-in-Transit Protection Missing', severity: 'high', clause_reference: 'NIST CSF PR.DS-2: Data-in-transit is protected', pattern: /(?:tls|ssl|https|encrypt.?in.?transit|transport.?security)/gi, negate: true, fileLevel: true, extensions: ['.js', '.ts', '.py', '.yaml'] },
  { rule_id: 'NIST-PR.DS-5', category: 'nist', title: 'Data Leak Protection Missing', severity: 'high', clause_reference: 'NIST CSF PR.DS-5: Protections against data leaks', pattern: /(?:data.?leak|dlp|exfiltration|data.?loss.?prevention)/gi, negate: true, fileLevel: true, extensions: ['.js', '.ts', '.py'] },
  { rule_id: 'NIST-PR.DS-6', category: 'nist', title: 'Integrity Check Missing', severity: 'medium', clause_reference: 'NIST CSF PR.DS-6: Integrity checking for software/data', pattern: /(?:integrity|checksum|hash.?verify|subresource.?integrity|sri)/gi, negate: true, fileLevel: true, extensions: ['.js', '.ts', '.html'] },
  { rule_id: 'NIST-PR.IP-1', category: 'nist', title: 'Baseline Configuration Missing', severity: 'medium', clause_reference: 'NIST CSF PR.IP-1: Baseline configuration created and maintained', pattern: /(?:baseline|hardening|benchmark|cis.?benchmark|security.?baseline)/gi, negate: true, fileLevel: true, extensions: ['.md', '.yaml', '.yml'] },
  { rule_id: 'NIST-PR.IP-12', category: 'nist', title: 'Vulnerability Management Plan Missing', severity: 'medium', clause_reference: 'NIST CSF PR.IP-12: Vulnerability management plan', pattern: /(?:vulnerability.?management|patch.?management|CVE.?tracking)/gi, negate: true, fileLevel: true, extensions: ['.md', '.yaml', '.yml'] },
  { rule_id: 'NIST-DE.AE-1', category: 'nist', title: 'Anomaly Detection Baseline Missing', severity: 'medium', clause_reference: 'NIST CSF DE.AE-1: Baseline of network operations established', pattern: /(?:baseline|normal.?behavior|anomaly.?detection|behavioral.?analysis)/gi, negate: true, fileLevel: true, extensions: ['.yaml', '.yml', '.js', '.ts'] },
  { rule_id: 'NIST-DE.CM-1', category: 'nist', title: 'Network Monitoring Not Configured', severity: 'high', clause_reference: 'NIST CSF DE.CM-1: Network is monitored for security events', pattern: /(?:network.?monitor|traffic.?analysis|pcap|netflow|siem)/gi, negate: true, fileLevel: true, extensions: ['.yaml', '.yml', '.js', '.ts'] },
  { rule_id: 'NIST-DE.CM-4', category: 'nist', title: 'Malicious Code Detection Missing', severity: 'high', clause_reference: 'NIST CSF DE.CM-4: Malicious code is detected', pattern: /(?:antivirus|malware|av.?scan|clamav|yara)/gi, negate: true, fileLevel: true, extensions: ['.yaml', '.yml'] },
  { rule_id: 'NIST-DE.CM-8', category: 'nist', title: 'Vulnerability Scans Not Performed', severity: 'medium', clause_reference: 'NIST CSF DE.CM-8: Vulnerability scans are performed', pattern: /(?:vuln.?scan|nessus|qualys|rapid7|nmap|openvas)/gi, negate: true, fileLevel: true, extensions: ['.yaml', '.yml', '.json'] },
  { rule_id: 'NIST-RS.RP-1', category: 'nist', title: 'Response Plan Not Documented', severity: 'medium', clause_reference: 'NIST CSF RS.RP-1: Response plan is executed during/after event', pattern: /(?:response.?plan|incident.?response|disaster.?recovery|business.?continuity)/gi, negate: true, fileLevel: true, extensions: ['.md', '.txt'] },
  { rule_id: 'NIST-RC.RP-1', category: 'nist', title: 'Recovery Plan Not Documented', severity: 'medium', clause_reference: 'NIST CSF RC.RP-1: Recovery plan is executed during/after event', pattern: /(?:recovery.?plan|backup.?restore|rto|rpo|disaster.?recovery)/gi, negate: true, fileLevel: true, extensions: ['.md', '.txt', '.yaml'] },

  // ── Docker/Container Security ─────────────────────────────────────────────
  { rule_id: 'CONT-SEC-001', category: 'sast', title: 'Docker Running as Root', severity: 'high', clause_reference: 'CIS Docker Benchmark 4.1, PCI DSS 6.2.4', pattern: /^(?!.*USER\s).*FROM/gim, extensions: ['.dockerfile'], fileLevel: true, negate: true },
  { rule_id: 'CONT-SEC-002', category: 'sast', title: 'Docker COPY/ADD of Secrets', severity: 'critical', clause_reference: 'CIS Docker Benchmark 4.10', pattern: /(?:COPY|ADD)\s+.*(?:\.env|\.key|\.pem|id_rsa|credentials|secret)/gi, extensions: ['Dockerfile', '.dockerfile'] },
  { rule_id: 'CONT-SEC-003', category: 'sast', title: 'Docker Image Using Latest Tag', severity: 'medium', clause_reference: 'CIS Docker Benchmark 4.7', pattern: /FROM\s+\S+:latest/gi, extensions: ['Dockerfile', '.dockerfile'] },
  { rule_id: 'CONT-SEC-004', category: 'sast', title: 'Privileged Container', severity: 'critical', clause_reference: 'CIS Docker Benchmark 5.4, PCI DSS 6.2.4', pattern: /privileged\s*:\s*true/gi, extensions: ['.yaml', '.yml'] },
  { rule_id: 'CONT-SEC-005', category: 'sast', title: 'Host Network Mode', severity: 'high', clause_reference: 'CIS Docker Benchmark 5.19', pattern: /network_mode\s*:\s*['"]?host/gi, extensions: ['.yaml', '.yml'] },

  // ── IaC Security (Terraform/K8s) ──────────────────────────────────────────
  { rule_id: 'IAC-SEC-001', category: 'sast', title: 'Security Group Allows 0.0.0.0/0 Ingress', severity: 'critical', clause_reference: 'PCI DSS 1.2.5, ISO 27001 A.8.20, NIST PR.AC-5', pattern: /(?:cidr_blocks|CidrIp)\s*[:=]\s*\[?\s*['"]0\.0\.0\.0\/0['"]/gi, extensions: ['.tf', '.json', '.yaml', '.yml'] },
  { rule_id: 'IAC-SEC-002', category: 'sast', title: 'S3 Bucket Public Access', severity: 'critical', clause_reference: 'PCI DSS 3.4.1, ISO 27001 A.8.3', pattern: /(?:acl\s*[:=]\s*['"]public|PublicReadWrite|block_public_acls\s*[:=]\s*false)/gi, extensions: ['.tf', '.json', '.yaml'] },
  { rule_id: 'IAC-SEC-003', category: 'sast', title: 'Database Not Encrypted', severity: 'high', clause_reference: 'PCI DSS 3.4.1, HIPAA 164.312(a)(2)(iv)', pattern: /(?:storage_encrypted|StorageEncrypted)\s*[:=]\s*false/gi, extensions: ['.tf', '.json', '.yaml'] },
  { rule_id: 'IAC-SEC-004', category: 'sast', title: 'Logging Not Enabled', severity: 'medium', clause_reference: 'PCI DSS 10.2.1, SOC2 CC7.1', pattern: /(?:enable_logging|logging|access_logs)\s*[:=]\s*false/gi, extensions: ['.tf', '.json', '.yaml'] },
  { rule_id: 'IAC-SEC-005', category: 'sast', title: 'K8s Pod Running as Root', severity: 'high', clause_reference: 'CIS Kubernetes Benchmark 5.2.6', pattern: /runAsUser\s*:\s*0\b/g, extensions: ['.yaml', '.yml'] },
  { rule_id: 'IAC-SEC-006', category: 'sast', title: 'K8s Missing Network Policy', severity: 'medium', clause_reference: 'CIS Kubernetes Benchmark 5.3.2', pattern: /kind\s*:\s*NetworkPolicy/gi, negate: true, fileLevel: true, extensions: ['.yaml', '.yml'] },
  { rule_id: 'IAC-SEC-007', category: 'sast', title: 'K8s Missing Resource Limits', severity: 'medium', clause_reference: 'CIS Kubernetes Benchmark 5.4.1', pattern: /resources\s*:\s*\n\s*limits/gi, negate: true, fileLevel: true, extensions: ['.yaml', '.yml'] },

  // ── Architecture & Code Quality ───────────────────────────────────────────
  { rule_id: 'ARCH-001', category: 'sast', title: 'Circular Dependency Detected', severity: 'medium', clause_reference: 'ISO 27001 A.8.28: Secure coding', pattern: /(?:require\(['"]\.\.\/.*require\(['"]\.\.\/|from\s+['"]\.\.\/.*from\s+['"]\.\.\/)/gim, extensions: ['.js', '.ts', '.py'] },
  { rule_id: 'ARCH-002', category: 'sast', title: 'God Object/File (>500 lines)', severity: 'low', clause_reference: 'ISO 27001 A.8.28', pattern: null, lineThreshold: 500, extensions: ['.js', '.ts', '.py', '.java', '.rb', '.go'] },
  { rule_id: 'ARCH-003', category: 'sast', title: 'Mixed Concerns in Single Module', severity: 'low', clause_reference: 'ISO 27001 A.8.28', pattern: /(?:import.*(?:express|fastify|koa))[\s\S]*(?:import.*(?:mongoose|sequelize|prisma|knex))/gim, fileLevel: true, extensions: ['.js', '.ts'] },
  { rule_id: 'ARCH-004', category: 'sast', title: 'TODO/FIXME Security Items Left Unresolved', severity: 'low', clause_reference: 'ISO 27001 A.8.28', pattern: /(?:TODO|FIXME|HACK|XXX|SECURITY|VULN)/gi, extensions: null },
  { rule_id: 'ARCH-005', category: 'sast', title: 'Wildcard Import', severity: 'low', clause_reference: 'ISO 27001 A.8.28', pattern: /from\s+\S+\s+import\s+\*/g, extensions: ['.py'] },

  // ── Supply Chain ──────────────────────────────────────────────────────────
  { rule_id: 'SUPPLY-001', category: 'sast', title: 'No Package Integrity Verification', severity: 'medium', clause_reference: 'NIST SP 800-53 SA-12, PCI DSS 6.3', pattern: /(?:integrity|sha256|sha512|checksum|verify)/gi, negate: true, fileLevel: true, extensions: ['.json'] },
  { rule_id: 'SUPPLY-002', category: 'sast', title: 'Typosquatting Risk: Unusual Package Name', severity: 'medium', clause_reference: 'NIST SP 800-53 SA-12', pattern: /"(?:colorsss|event-stream-fake|crossenv|babelcli|opencollective-postinstall)"/gi, extensions: ['.json'] },

  // ── SOC 1 ─────────────────────────────────────────────────────────────────
  { rule_id: 'SOC1-001', category: 'sast', title: 'Hardcoded Financial Secrets/Tokens', severity: 'critical', clause_reference: 'SOC 1 CC6.1, CC6.2', pattern: /(?:stripe_key|plaid_secret|braintree_key|paypal_token)\s*[:=]\s*["'][A-Za-z0-9_-]{10,}["']/gi, extensions: ['.js', '.ts', '.py', '.java', '.rb'] },
  { rule_id: 'SOC1-002', category: 'sast', title: 'Missing Audit Logging on Transaction', severity: 'high', clause_reference: 'SOC 1 CC7.1', pattern: /function\s+(?:processTransaction|transferFunds|executePayment)[\s\S]{0,150}(?!.*(?:audit|log|record))/gi, extensions: ['.js', '.ts', '.py', '.java'] },

  // ── GLBA ──────────────────────────────────────────────────────────────────
  { rule_id: 'GLBA-001', category: 'sast', title: 'Insecure PII Storage (No Encryption)', severity: 'critical', clause_reference: 'GLBA Safeguards Rule 314.4(c)(3)', pattern: /(?:ssn|social_security|credit_card|account_number)\s*[:=]\s*(?:req\.body|event\.body)\.[a-zA-Z0-9_]+(?!\s*\.\s*(?:encrypt|hash))/gi, extensions: ['.js', '.ts', '.py'] },
  { rule_id: 'GLBA-002', category: 'sast', title: 'Transmission of Unencrypted Financial Data', severity: 'high', clause_reference: 'GLBA Safeguards Rule 314.4(c)(4)', pattern: /http:\/\/[a-zA-Z0-9.-]+\/(?:checkout|payment|billing|bank)/gi, extensions: ['.js', '.ts', '.html', '.py'] },

  // ── FISMA ─────────────────────────────────────────────────────────────────
  { rule_id: 'FISMA-001', category: 'sast', title: 'Weak Cryptographic Algorithm (FISMA/FIPS)', severity: 'high', clause_reference: 'FISMA FIPS 140-2, NIST SP 800-53 SC-13', pattern: /crypto\.createHash\(['"](?:md5|sha1)['"]\)/gi, extensions: ['.js', '.ts'] },
  { rule_id: 'FISMA-002', category: 'sast', title: 'System Auditing Disabled', severity: 'medium', clause_reference: 'FISMA NIST SP 800-53 AU-2', pattern: /(?:audit_enabled|AUDIT_LOGGING)\s*[:=]\s*false/gi, extensions: ['.js', '.ts', '.py', '.json', '.yaml'] },

  // ── NYDFS ─────────────────────────────────────────────────────────────────
  { rule_id: 'NYDFS-001', category: 'sast', title: 'MFA Not Enforced', severity: 'critical', clause_reference: 'NYDFS 23 NYCRR 500.12', pattern: /(?:mfa_enabled|two_factor_auth)\s*[:=]\s*false/gi, extensions: ['.js', '.ts', '.json', '.yaml'] },
  { rule_id: 'NYDFS-002', category: 'sast', title: 'Insecure Data Retention Period', severity: 'high', clause_reference: 'NYDFS 23 NYCRR 500.13', pattern: /(?:retention_days|data_retention)\s*[:=]\s*(?:9999|-1|0)/gi, extensions: ['.js', '.ts', '.yaml', '.json'] }
];
module.exports = { COMPLIANCE_RULES };
